name: Update SVG Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Каждый день

jobs:
  generate_svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Generate SVG animation
        run: |
          # Создаем новый SVG файл с анимацией
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><rect x="150" y="350" width="100" height="10" fill="blue"><animate attributeName="x" from="150" to="300" dur="2s" repeatCount="indefinite" /></rect><rect x="150" y="0" width="30" height="30" fill="red"><animate attributeName="y" from="0" to="350" dur="3s" repeatCount="indefinite" /></rect><rect x="200" y="0" width="30" height="30" fill="green"><animate attributeName="y" from="0" to="350" dur="4s" repeatCount="indefinite" /></rect><rect x="250" y="0" width="30" height="30" fill="yellow"><animate attributeName="y" from="0" to="350" dur="5s" repeatCount="indefinite" /></rect></svg>' > generated_game.svg
        
      - name: Commit and push SVG file
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update SVG animation"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Публикуем в корень
          publish_branch: gh-pages  # Ветка, куда будет залит контент
